# Generated by Django 4.2.30 on 2026-10-06 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_virtual_user_job_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_titles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        # Preserve old-container inserts and retain existing names as one item.
        migrations.RunSQL(
            "ALTER TABLE users ALTER COLUMN job_titles SET DEFAULT '{}'::varchar(255)[]",
            "ALTER TABLE users ALTER COLUMN job_titles DROP DEFAULT",
        ),
        migrations.RunSQL(
            "UPDATE users SET job_titles = ARRAY[job_title] WHERE job_title <> '' AND cardinality(job_titles) = 0",
            migrations.RunSQL.noop,
        ),
    ]
