# Generated by Django 4.2.30 on 2026-10-07 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_user_job_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemember",
            name="job_titles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=None, null=True, size=None
            ),
        ),
    ]
